AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Demonstrate a basic fact skill built with the ASK NodeJS SDK
Resources:
  serverlessrepoclansmanalexaskillskitnodejsfactsk1RE7SEYH1C50R:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: .
      Description: Demonstrate a basic fact skill built with the ASK NodeJS SDK
      MemorySize: 128
      Timeout: 7
      Role: >-
        arn:aws:iam::491329690418:role/serverlessrepo-clansman-alexaskillskitnodejsfactsk-1LNOJ6ZBBW4P6
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
      Tags:
        'serverlessrepo:semanticVersion': 2.0.2
        'serverlessrepo:applicationId': >-
          arn:aws:serverlessrepo:us-east-1:173334852312:applications/alexa-skills-kit-nodejs-factskill
